###
GET http://localhost:8000/

###
GET http://localhost:8000/api/projects?page=1

###
POST http://localhost:8000/api/projects
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john@example.com",
    "subject": "New Project Proposal",
    "description": "This is a test project submission"
}

###
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
    "username": "niconet1",
    "password": "iWillBSmthg"
}

### Create Tunnel
POST http://localhost:8000/api/tunnel/provision


### Expected Response:
# {
#   "success": true,
#   "data": {
#     "configYml": "...",
#     "tunnelJsonBase64": "...",
#     "hostname": "test-device-001.yourdomain.com"
#   }
# }

### Test Cloudflare API Directly
# @name createTunnel
POST https://api.cloudflare.com/client/v4/accounts/8f8cbcebaac730c4876925325c9bc441/cfd_tunnel
Content-Type: application/json
Authorization: Bearer IcMcuPz-5PVp-TmlfyOkSR1Mz9cX66NJ2GSsiWxw

{
  "name": "api-tunnel",
  "config_src": "cloudflare"
}